batch_size: 1
data_name: manifold40
data_root: ./datasets
epochs: 1
epochs_sphere: 200
gpus:
- - 0
latent_dim: 1024
lmbda: 1.0
load_make_sphere: false
loss_func: MSL2
lr: 1.0e-05
model_name: LC
norm: false
norm10: false
pretrain: false
